Repository BV-BRC/BV-BRC-Docs, pull requests merged in 2023-01, with the labels that each got.

#79 Fix old patric-cli naming reference
  docroot/cli_tutorial/cli_installation.rst
Labels: bug

#82 Update copyright year and author
  docroot/conf.py
Labels: enhancement

#84 Updated April l UVA workshop notice
  docroot/news/2023/2023-01-02-bv-brc-workshop-uva.rst
Labels: minor doc update
